MileageDiaryWeb2/DiaryApp/urls.py
'''
Created on 2020/07/14

@author: snowc
'''
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'DiaryApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('<int:log_id>/', views.detail, name='detail'),
    path('<int:log_id>/results/', views.results, name='results'),
    path('<int:log_id>/vote/', views.addLog, name='addLog'),
    path('DiaryApp_list', views.LogListView.as_view(), name='DiaryApp_list'),
    path('create/', views.LogCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LogDeleteView.as_view(), name='delete'),
    path('log_chart/', views.ChartView, name='chart'),
    path('login/', auth_views.LoginView.as_view(template_name='DiaryApp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('oauth/', include('social_django.urls', namespace='social')),
]

MileageDiaryWeb2/MileageDiaryWeb2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # ex: /polls/
    path('DiaryApp/', include('DiaryApp.urls')),
    path('admin', admin.site.urls),
]

#urlpatterns = [
#    path('MileageDiaryWeb2/', include('MileageDiaryWeb2.urls')),
#    path('MileageDiaryWeb2.DiaryApp.admin/', admin.site.urls),
#]

MileageDiaryWeb2/DiaryApp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from django.contrib.auth import get_user_model

# Create your models here.
def check_km(value):
    if value < 0 or value > 1000:
        raise ValidationError('正しい距離(0~1000km)を入力してください。')
def check_litter(value):
    if value < 0 or value > 100:
        raise ValidationError('正しい量(0~100L)を入力してください。')
def check_price(value):
    if value < 0 or value > 300:
        raise ValidationError('正しい単価(0~300円)を入力してください。')

class Log(models.Model):
    km = models.DecimalField(max_digits=6, decimal_places=2, validators=[check_km])
    litter = models.DecimalField(max_digits=5, decimal_places=2, validators=[check_litter])
    price = models.IntegerField(validators=[check_price])
    trip_memo = models.CharField(max_length=100, validators=[MaxLengthValidator(100, '100文字以内にしてください。')])
    updated_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    
    def __str__(self):
        return self.trip_memo
    
    def was_published_recently(self):
        return self.updated_at >= timezone.now() - datetime.timedelta(days=1)

MileageDiaryWeb2/DiaryApp/views.py

# Create your views here.
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.views.generic import ListView
from django.views.generic import UpdateView, CreateView, DeleteView, TemplateView
from django.urls import reverse
from .models import Log
from django.db.models import Q
from django.urls.base import reverse_lazy
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from DiaryApp.templatetags import utils
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
import datetime

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('DiaryApp:index')
    else:
        form = UserCreationForm()
    return render(request, 'DiaryApp/signup.html', {'form': form})

def index(request):
    return render(request, 'DiaryApp/index.html')

@login_required
def home(request):

    log = Log.objects.filter(author_id = request.user.id).order_by('-updated_at')
    return render(request, 'DiaryApp/home.html', {'log': log})

def detail(request, log_id):
    logKm = get_object_or_404(Log, pk=log_id)
    return render(request, 'DiaryApp/detail.html', {'logKm': logKm})

def results(request, log_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % log_id)

def addLog(request, log_id):
    response = "You're looking at the addLog of question %s."
    return HttpResponse(response % log_id)

#一覧表示用のDjango標準ビュー(ListView)を承継して一覧表示用のクラスを定義
class LogListView(LoginRequiredMixin, ListView):
    #利用するモデルを指定
#    model = Log
    #データを渡すテンプレートファイルを指定
    template_name = 'DiaryApp/DiaryApp_list.html'
    #pagination
    paginate_by = 10
    #家計簿テーブルの全データを取得するメソッドを定義
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す
        context["user"] = self.request.user
        return context
    def get_queryset(self):
        q_word = self.request.GET.get('query')

        if q_word:
            object_list = Log.objects.filter(
                Q(trip_memo__icontains=q_word), author_id = self.request.user.id)
        else:
            object_list = Log.objects.filter(author_id = self.request.user.id)
        return object_list

@login_required
@csrf_exempt
def ChartView(request, *args, **kwargs):
    passId = request.user
    if Log.objects.filter(author_id = request.user.id).values_list('km', flat=True):
        if request.POST.get('y1axis') in {'km', 'totalKm', 'litter', 'totalLitter', 'mileage', 'aveMileage', 'price', 'cost', 'totalCost'}:
            y1_list = utils.chartUtils(passId, request.POST.get('y1axis'))
            y1_label = utils.chartLabel(request.POST.get('y1axis'))
        else:
            y1_list = Log.objects.filter(author_id = request.user.id).values_list('km', flat=True)
            y1_label = '距離'

        if request.POST.get('y2axis') in {'km', 'totalKm', 'litter', 'totalLitter', 'mileage', 'aveMileage', 'price', 'cost', 'totalCost'}:
            y2_list = utils.chartUtils(passId, request.POST.get('y2axis'))
            y2_label = utils.chartLabel(request.POST.get('y2axis'))
        else:
            y2_list = Log.objects.values_list('litter', flat=True)
            y2_label = '給油量'
        x_list = []
        for x in Log.objects.filter(author_id = request.user.id).values_list('updated_at', flat=True):
            x_list.append(x.strftime('%Y/%m/%d'))
    else:
        y1_list = [0]
        y2_list =[0]
        y1_label = 'No Data'
        y2_label = 'No Data'
        x_list = [0]

    y1max = max(y1_list)
    y1min = min(y1_list)
    y2max = max(y2_list)
    y2min = min(y2_list)
    return render(request, 'DiaryApp/log_chart.html', {'x_list' : x_list, 'y1_list' : y1_list, 'y2_list' : y2_list, 'y1_label' : y1_label, 'y2_label' : y2_label, 'y1max' : y1max, 'y2max' : y2max, 'y1min' : y1min, 'y2min' : y2min})

@login_required
def log_delete(request, log_id):
    logId = get_object_or_404(Log, pk=log_id)
    return render(request, 'DiaryApp/log_delete.html', {'logId': logId})


class LogUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'DiaryApp/log_update_form.html'
    model = Log
    fields = ['km', 'litter', 'price', 'trip_memo']

    def get_success_url(self):
        return reverse('DiaryApp:DiaryApp_list')

    def get_form(self):
        form = super(LogUpdateView, self).get_form()
        form.fields['km'].label = '走行距離'
        form.fields['litter'].label = '給油量'
        form.fields['price'].label = 'ガソリン単価'
        form.fields['trip_memo'].label = 'メモ'
        return form

class LogCreateView(LoginRequiredMixin, CreateView):
    template_name = 'DiaryApp/log_create_form.html'
    model = Log
    fields = ['km', 'litter', 'price', 'trip_memo']

    def form_valid(self, form):
        post = form.save(commit=False)
        # employeeフィールドはログインしているユーザ名とする
        post.author_id = self.request.user.id
        post.save()
        return redirect('DiaryApp:DiaryApp_list')

class LogDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'DiaryApp/log_delete.html'
    model = Log

    success_url = reverse_lazy('DiaryApp:DiaryApp_list')

def userId(request):
    userId = request.user.id
    return userId

def mileage(value, args):
    return round(value / args, 2)

def cost(value, args):
    return round(value * args, 0)

def totalKm(request, value):
    kmList = Log.objects.filter(author_id = request.user.id).values_list("km", flat=True).filter(id__range=(1, value))
    km = 0
    for itemKm in kmList:
        km += itemKm
    return km

def totalLitter(request, value):
    litterList = Log.objects.filter(author_id = request.user.id).values_list("litter", flat=True).filter(id__range=(1, value))
    litter = 0
    for itemLitter in litterList:
        litter += itemLitter
    return litter

def averageMileage(value):
    averageMileage = totalKm(value) / totalLitter(value)
    return round(averageMileage, 2)

def totalCost(value):
    litterList = Log.objects.values_list("litter", flat=True).filter(id__range=(1, value))
    priceList = Log.objects.values_list("price", flat=True).filter(id__range=(1, value))
    cost = 0
    for itemLitter, itemPrice in zip(litterList, priceList):
        cost += itemLitter * itemPrice
    return round(cost,0)

def chartKm():
    kmList = []
    for km in Log.objects.values_list("km", flat=True):
        kmList.append(km)
    return kmList

def chartId():
    idList = []
    for i in range(len(Log.objects.values_list("id", flat=True))):
        i += 1
        idList.append(i)
    return idList

def chartUtils(request, value):
    if value in {'km', 'litter', 'price'}:
        yaxis = value
        ylist = Log.objects.filter(author_id = request.user.id).values_list(f'{yaxis}', flat=True)
    elif value in {'totalKm'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            ylist.append(totalKm(ids))
    elif value in {'totalLitter'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            ylist.append(totalLitter(ids))
    elif value in {'mileage'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            km = Log.objects.values_list('km', flat=True).get(pk=ids)
            litter = Log.objects.values_list('litter', flat=True).get(pk=ids)
            ylist.append(mileage(km, litter))
    elif value in {'aveMileage'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            ylist.append(averageMileage(ids))
    elif value in {'cost'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            price = Log.objects.values_list('price', flat=True).get(pk=ids)
            litter = Log.objects.values_list('litter', flat=True).get(pk=ids)
            ylist.append(cost(price, litter))
    elif value in {'totalCost'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            ylist.append(totalCost(ids))
    else:
        yaxis = 'km'
        ylist = Log.objects.values_list(f'{yaxis}', flat=True)

    return ylist

MileageDiaryWeb2/DiaryApp/templates/base/navbar.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<style>
@import url('https://fonts.googleapis.com/css?family=Noto+Sans+JP');
.navbar-brand {
  background: -webkit-linear-gradient(#3498db 0%, #9b59b6 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
div{
  font-family: 'Noto Sans JP', sans-serif;
  margin: 0px 5px;
}
form{
  font-family: 'Noto Sans JP', sans-serif;
  margin: 0px 5px;
}
p{
  font-family: 'Noto Sans JP', sans-serif;
}
li{
margin: auto 0px;
}
.navlog{
margin: auto 0px;
}
</style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <a class="navbar-brand" href="{% url 'DiaryApp:index' %}">MileageDiary</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'DiaryApp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          メニュー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'DiaryApp:DiaryApp_list' %}">Log 詳細一覧</a>
          <a class="dropdown-item" href="{% url 'DiaryApp:chart' %}">Log グラフ</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'DiaryApp:create' %}">新規Log追加</a>
        </div>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ログアウト
        </a>
        <div class="dropdown-menu" aria-labelledby="navbardropdown">
          
          <a class="dropdown-item" href="{% url 'DiaryApp:logout' %}">ログアウト</a>
          
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          アカウント管理
        </a>
        <div class="dropdown-menu" aria-labelledby="navbardropdown">
          <a class="dropdown-item" href="{% url 'DiaryApp:password_change' %}">パスワード変更</a>
          
        </div>
      </li>
      {% else %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ログイン
        </a>
        <div class="dropdown-menu" aria-labelledby="navbardropdown">
          <a class="dropdown-item" href="{% url 'DiaryApp:login' %}">ログイン</a>
          
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'DiaryApp:signup' %}">アカウント登録</a>
        </div>
      </li>
      {% endif %}
      <li class="nav-item">
      	<a class="nav-link disabled" href="#">
        {% if user.is_authenticated %}
		<p class="navlog">{{ user.get_username }}でログイン中</p>
		{% else %}
		<p class="navlog">ログインしていません</p>
		{% endif %}</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'DiaryApp:DiaryApp_list' %}" method="get">
      <input class="form-control mr-sm-2" name="query" value="{{ request.GET.query }}" type="search" placeholder="メモから検索" aria-label="メモから検索">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</body>
</html>