MileageDiaryWeb2/DiaryApp/urls.py
'''
Created on 2020/07/14

@author: snowc
'''
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'DiaryApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('<int:log_id>/', views.detail, name='detail'),
    path('<int:log_id>/results/', views.results, name='results'),
    path('<int:log_id>/vote/', views.addLog, name='addLog'),
    path('DiaryApp_list', views.LogListView.as_view(), name='DiaryApp_list'),
    path('create/', views.LogCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LogDeleteView.as_view(), name='delete'),
    path('log_chart/', views.ChartView, name='chart'),
    path('login/', auth_views.LoginView.as_view(template_name='DiaryApp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('oauth/', include('social_django.urls', namespace='social')),
]

MileageDiaryWeb2/MileageDiaryWeb2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # ex: /polls/
    path('DiaryApp/', include('DiaryApp.urls')),
    path('admin', admin.site.urls),
]

#urlpatterns = [
#    path('MileageDiaryWeb2/', include('MileageDiaryWeb2.urls')),
#    path('MileageDiaryWeb2.DiaryApp.admin/', admin.site.urls),
#]

MileageDiaryWeb2/DiaryApp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from django.contrib.auth import get_user_model

# Create your models here.
def check_km(value):
    if value < 0 or value > 1000:
        raise ValidationError('正しい距離(0~1000km)を入力してください。')
def check_litter(value):
    if value < 0 or value > 100:
        raise ValidationError('正しい量(0~100L)を入力してください。')
def check_price(value):
    if value < 0 or value > 300:
        raise ValidationError('正しい単価(0~300円)を入力してください。')

class Log(models.Model):
    km = models.DecimalField(max_digits=6, decimal_places=2, validators=[check_km])
    litter = models.DecimalField(max_digits=5, decimal_places=2, validators=[check_litter])
    price = models.IntegerField(validators=[check_price])
    trip_memo = models.CharField(max_length=100, validators=[MaxLengthValidator(100, '100文字以内にしてください。')])
    updated_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    
    def __str__(self):
        return self.trip_memo
    
    def was_published_recently(self):
        return self.updated_at >= timezone.now() - datetime.timedelta(days=1)

MileageDiaryWeb2/DiaryApp/views.py

# Create your views here.
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.views.generic import ListView
from django.views.generic import UpdateView, CreateView, DeleteView, TemplateView
from django.urls import reverse
from .models import Log
from django.db.models import Q
from django.urls.base import reverse_lazy
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from DiaryApp.templatetags import utils
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
import datetime

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('DiaryApp:index')
    else:
        form = UserCreationForm()
    return render(request, 'DiaryApp/signup.html', {'form': form})

def index(request):
    return render(request, 'DiaryApp/index.html')

@login_required
def home(request):

    log = Log.objects.filter(author_id = request.user.id).order_by('-updated_at')
    return render(request, 'DiaryApp/home.html', {'log': log})

def detail(request, log_id):
    logKm = get_object_or_404(Log, pk=log_id)
    return render(request, 'DiaryApp/detail.html', {'logKm': logKm})

def results(request, log_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % log_id)

def addLog(request, log_id):
    response = "You're looking at the addLog of question %s."
    return HttpResponse(response % log_id)

#一覧表示用のDjango標準ビュー(ListView)を承継して一覧表示用のクラスを定義
class LogListView(LoginRequiredMixin, ListView):
    #利用するモデルを指定
#    model = Log
    #データを渡すテンプレートファイルを指定
    template_name = 'DiaryApp/DiaryApp_list.html'
    #pagination
    paginate_by = 10
    #家計簿テーブルの全データを取得するメソッドを定義
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す
        context["user"] = self.request.user
        return context
    def get_queryset(self):
        q_word = self.request.GET.get('query')

        if q_word:
            object_list = Log.objects.filter(
                Q(trip_memo__icontains=q_word), author_id = self.request.user.id)
        else:
            object_list = Log.objects.filter(author_id = self.request.user.id)
        return object_list

@login_required
@csrf_exempt
def ChartView(request, *args, **kwargs):
    passId = request.user
    if Log.objects.filter(author_id = request.user.id).values_list('km', flat=True):
        if request.POST.get('y1axis') in {'km', 'totalKm', 'litter', 'totalLitter', 'mileage', 'aveMileage', 'price', 'cost', 'totalCost'}:
            y1_list = utils.chartUtils(passId, request.POST.get('y1axis'))
            y1_label = utils.chartLabel(request.POST.get('y1axis'))
        else:
            y1_list = Log.objects.filter(author_id = request.user.id).values_list('km', flat=True)
            y1_label = '距離'

        if request.POST.get('y2axis') in {'km', 'totalKm', 'litter', 'totalLitter', 'mileage', 'aveMileage', 'price', 'cost', 'totalCost'}:
            y2_list = utils.chartUtils(passId, request.POST.get('y2axis'))
            y2_label = utils.chartLabel(request.POST.get('y2axis'))
        else:
            y2_list = Log.objects.values_list('litter', flat=True)
            y2_label = '給油量'
        x_list = []
        for x in Log.objects.filter(author_id = request.user.id).values_list('updated_at', flat=True):
            x_list.append(x.strftime('%Y/%m/%d'))
    else:
        y1_list = [0]
        y2_list =[0]
        y1_label = 'No Data'
        y2_label = 'No Data'
        x_list = [0]

    y1max = max(y1_list)
    y1min = min(y1_list)
    y2max = max(y2_list)
    y2min = min(y2_list)
    return render(request, 'DiaryApp/log_chart.html', {'x_list' : x_list, 'y1_list' : y1_list, 'y2_list' : y2_list, 'y1_label' : y1_label, 'y2_label' : y2_label, 'y1max' : y1max, 'y2max' : y2max, 'y1min' : y1min, 'y2min' : y2min})

@login_required
def log_delete(request, log_id):
    logId = get_object_or_404(Log, pk=log_id)
    return render(request, 'DiaryApp/log_delete.html', {'logId': logId})


class LogUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'DiaryApp/log_update_form.html'
    model = Log
    fields = ['km', 'litter', 'price', 'trip_memo']

    def get_success_url(self):
        return reverse('DiaryApp:DiaryApp_list')

    def get_form(self):
        form = super(LogUpdateView, self).get_form()
        form.fields['km'].label = '走行距離'
        form.fields['litter'].label = '給油量'
        form.fields['price'].label = 'ガソリン単価'
        form.fields['trip_memo'].label = 'メモ'
        return form

class LogCreateView(LoginRequiredMixin, CreateView):
    template_name = 'DiaryApp/log_create_form.html'
    model = Log
    fields = ['km', 'litter', 'price', 'trip_memo']

    def form_valid(self, form):
        post = form.save(commit=False)
        # employeeフィールドはログインしているユーザ名とする
        post.author_id = self.request.user.id
        post.save()
        return redirect('DiaryApp:DiaryApp_list')

class LogDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'DiaryApp/log_delete.html'
    model = Log

    success_url = reverse_lazy('DiaryApp:DiaryApp_list')

def userId(request):
    userId = request.user.id
    return userId

def mileage(value, args):
    return round(value / args, 2)

def cost(value, args):
    return round(value * args, 0)

def totalKm(request, value):
    kmList = Log.objects.filter(author_id = request.user.id).values_list("km", flat=True).filter(id__range=(1, value))
    km = 0
    for itemKm in kmList:
        km += itemKm
    return km

def totalLitter(request, value):
    litterList = Log.objects.filter(author_id = request.user.id).values_list("litter", flat=True).filter(id__range=(1, value))
    litter = 0
    for itemLitter in litterList:
        litter += itemLitter
    return litter

def averageMileage(value):
    averageMileage = totalKm(value) / totalLitter(value)
    return round(averageMileage, 2)

def totalCost(value):
    litterList = Log.objects.values_list("litter", flat=True).filter(id__range=(1, value))
    priceList = Log.objects.values_list("price", flat=True).filter(id__range=(1, value))
    cost = 0
    for itemLitter, itemPrice in zip(litterList, priceList):
        cost += itemLitter * itemPrice
    return round(cost,0)

def chartKm():
    kmList = []
    for km in Log.objects.values_list("km", flat=True):
        kmList.append(km)
    return kmList

def chartId():
    idList = []
    for i in range(len(Log.objects.values_list("id", flat=True))):
        i += 1
        idList.append(i)
    return idList

def chartUtils(request, value):
    if value in {'km', 'litter', 'price'}:
        yaxis = value
        ylist = Log.objects.filter(author_id = request.user.id).values_list(f'{yaxis}', flat=True)
    elif value in {'totalKm'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            ylist.append(totalKm(ids))
    elif value in {'totalLitter'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            ylist.append(totalLitter(ids))
    elif value in {'mileage'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            km = Log.objects.values_list('km', flat=True).get(pk=ids)
            litter = Log.objects.values_list('litter', flat=True).get(pk=ids)
            ylist.append(mileage(km, litter))
    elif value in {'aveMileage'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            ylist.append(averageMileage(ids))
    elif value in {'cost'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            price = Log.objects.values_list('price', flat=True).get(pk=ids)
            litter = Log.objects.values_list('litter', flat=True).get(pk=ids)
            ylist.append(cost(price, litter))
    elif value in {'totalCost'}:
        ylist = []
        for ids in Log.objects.values_list('id', flat=True):
            ylist.append(totalCost(ids))
    else:
        yaxis = 'km'
        ylist = Log.objects.values_list(f'{yaxis}', flat=True)

    return ylist

MileageDiaryWeb2/DiaryApp/templates/DiaryApp/DiaryApp_list.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"  name=”viewport” content=”width=device-width,initial-scale=1.0>
<title>Logデータ一覧</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="styleSheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/css/theme.default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.widgets.min.js"></script>
<style>
@import url('https://fonts.googleapis.com/css?family=Noto+Sans+JP');
table{
  width: 100%;
  table:striped; 
  table:bordered;
  table:hover;
  overflow-x: scroll;
  white-space: nowrap;
  -webkit-overflow-scrolling: touch;
}
th,td{
  border:solid 1px #aaaaaa;
}
td{
  text-align: center;
}
th {
  font-weight: bold;
  vertical-align: top;
  background: #3f3f3f;
  color: #ffffff;
}
a.btn1{
  font-family: 'Noto Sans JP', sans-serif;
  width: 100%
  display: inline-block;
  color: #485859;
  text-decoration: none;
  border: 2px solid #00bfff;
  padding: 0px 2px;
  margin: 1px 1px;
  font-weight: bold;
  border-radius: 2px;
  transition: .4s;
}
.btn1:hover {
  background-color: #00bfff;
  border-color: #007bbb;
  color: #FFF;
}
a.btn2{
  font-family: 'Noto Sans JP', sans-serif;
  width: 100%
  display: inline-block;
  color: #485859;
  text-decoration: none;
  border: 2px solid #ff4500;
  padding: 0px 2px;
  margin: 1px 1px;
  font-weight: bold;
  border-radius: 2px;
  transition: .4s;
}
.btn2:hover {
  background-color: #ff4500;
  border-color: #e2041b;
  color: #FFF;
}
a.btn3{
  font-family: 'Noto Sans JP', sans-serif;
  font-size: 16px;
  display: inline-block;
  color: #9ec34b;
  text-decoration: none;
  margin: 10px 5px 10px 20px;
  border: 2px solid #9ec34b;
  padding: 8px 16px;
  font-weight: bold;
  border-radius: 4px;
  transition: .4s;
}
.btn3:hover {
  background-color: #9ec34b;
  border-color: #cbe585;
  color: #FFF;
}
tr:nth-child(even) {
  background: #d9d9d9;
 }
h1 {
  font-family: 'Noto Sans JP', sans-serif;
  background: -webkit-linear-gradient(#3498db 0%, #9b59b6 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  float: left;
  margin: 5px 5px;
  padding: 5px 5px;
}
@media screen and (min-width: 480px) {
}
@media screen and (max-width: 479px) {
.scroll-table{
overflow: auto;
white-space: nowrap;
width: 100%;
}
}
</style>
<!-- noConflict関数でjQuery競合を回避　https://www.buildinsider.net/web/jqueryref/067 -->
<script>
var $j = jQuery.noConflict(true);
$j(document).ready(function() {
	$j("#ListView").tablesorter({
		headers: {
            9: { sorter: false },
            11: { sorter: false }
         }
	});
	}); 
</script>
</head>
<body>
{% extends "DiaryApp/layout.html" %}
{% load utils %}
{% block content %}

<h1>Log一覧</h1> 
<a class="btn3" href="{% url 'DiaryApp:create'%}" role="button">新規作成</a>
         <!-- テーブル表の定義 -->
         <div class='scroll-table'>
          <table id=ListView class="tablesorter-default">
              <thead>
                <tr>
                  <th class="text-center">走行距離</th>
                  <th class="text-center">累計走行距離</th>
                  <th class="text-center">給油量</th>
                  <th class="text-center">合計給油量</th>
                  <th class="text-center">燃費</th>
                  <th class="text-center">平均燃費</th>
                  <th class="text-center">ガソリン単価</th>
                  <th class="text-center">ガソリン代</th>
                  <th class="text-center">累計ガソリン代</th>
                  <th class="text-center">メモ</th>
                  <th class="text-center">日付</th>
                  <th class="text-center">修正・削除</th>
                </tr>
              </thead>
            　<!-- ここまでが表の列の定義-->

            　<!-- 表のデータ部分の表示-->
            
              <tbody>
              {% with userId=user.id %}
              {% for log in object_list %}
                  <tr class="odd gradeX text-center">
                    <td class="text-center" width="40">{{ log.km}}km</td>
                    <td class="text-center" width="80">{%  totalKm userId log.id %}km</td>
                    <td class="text-center" width="50">{{ log.litter }}L</td>
                    <td class="text-center" width="70">{% totalLitter userId log.id %}L</td>
                    <td class="text-center" width="40">{{ log.km | mileage:log.litter}}km/L</td>
                    <td class="text-center" width="40">{% averageMileage userId log.id %}km/L</td>
                    <td class="text-center" width="80">{{ log.price }}円/L</td>
                    <td class="text-center" width="70">{{ log.price | cost:log.litter }}円</td>
                    <td class="text-center" width="90">{% totalCost userId log.id %}円</td>
                    <td class="text-center" width="160">{{ log.trip_memo }}</td>
                    <td class="text-center" width="100">{{ log.updated_at }}</td>
                    <td class="text-center" width="70">
                <a class="btn1" href="{% url 'DiaryApp:update' log.pk %}" role="button">修正</a>
                <a class="btn2" href="{% url 'DiaryApp:delete' log.pk %}" role="button">削除</a>
               </td>
                  </tr>
              {% endfor %}
              {% endwith %}
              </tbody>
            　<!-- ここまでが表のデータ部分の表示-->

            </table>
            </div>
            <!-- ここまでがテーブル表の定義 -->
{% include "DiaryApp/pagination.html" %}

{% endblock content %}


</body>
</html>

MileageDiaryWeb2/DiaryApp/templates/DiaryApp/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>detail</title>
</head>
<body>
{{ log }}
<h1>{{ log.trip_memo }}</h1>
{% if logKm %}
    	<ul>
        	<li>{{ log.km }}</li>
    	</ul>
	{% else %}
    	<p>No DiaryApp are available.</p>
	{% endif %}
</body>
</html>

MileageDiaryWeb2/DiaryApp/templates/DiaryApp/home.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name=”viewport” content=”width=device-width,initial-scale=1.0″>
<title>MileageDiary トップページ</title>
<style>
h2{
background: -webkit-linear-gradient(#3498db 0%, #9b59b6 100%);
-webkit-background-clip: text;
-webkit-text-fill-color: transparent;
text-align: center;
margin: 5px 5px;
padding: 5px 5px;
}
div{
width: 70%;
margin: 0px auto;
}
@media screen and (min-width: 480px) {
}
@media screen and (max-width: 479px) {
div{
width: 95%;
}
}
</style>
</head>
  <body>
  {% extends "DiaryApp/layout.html" %}
  {% block content %}
  <h2 style="text-align: center;">HOME</h2>
  <div>
  <h3>最近の更新</h3>
    <hr />
    {% for log in log %}
    <div>
      <h3>{{ log.trip_memo }}</h3>
      <div>{{ log.km }}km, {{ log.litter }}L, 更新日: {{ log.updated_at }}</div>
    </div>
    <hr />
    {% endfor %}
  </div>
  {% endblock %}
</body>
</html>

MileageDiaryWeb2/DiaryApp/templates/DiaryApp/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8"  name=”viewport” content=”width=device-width,initial-scale=1.0>
    <title>MileageDiary index</title>
    <style>
    @import url('https://fonts.googleapis.com/css?family=Noto+Sans+JP');
    *{
    font-family: 'Noto Sans JP', sans-serif;
    }
    h1{
    background: -webkit-linear-gradient(#3498db 0%, #9b59b6 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    text-align: center;
    margin: 5px 5px;
    padding: 5px 5px;
    }
    p{
    font-size: large;
    }
    .main{
    text-align: center;
    margin: 10px 5px;
    padding: 10px 5px;
    }
    .link{
    display: flex;
    justify-content: center;
    text-align: center;
    }
    .signupbtn, .loginbtn, .logoutbtn{
    align: center;
    border-radius : 9%;          /* 角丸       */
    cursor        : pointer;     /* カーソル   */
    color         : #ffffff;     /* 文字色     */
    line-height   : 1em;         /* 1行の高さ  */
    transition    : .3s;         /* なめらか変化 */
    box-shadow    : 2px 2px 1px #666666;  /* 影の設定 */
    }
    .signupbtn{
    background    : #5d627b;     /* 背景色     */
    border        : 2px solid #5d627b;    /* 枠の指定 */
    }
    .loginbtn{
    background    : #556b2f;     /* 背景色     */
    border        : 2px solid #556b2f;    /* 枠の指定 */
    }
    .logoutbtn{
    background    : #ff4500;     /* 背景色     */
    border        : 2px solid #ff4500;    /* 枠の指定 */
    }
    .signupbtn:hover {
    box-shadow    : none;        /* カーソル時の影消去 */
    color         : #5d627b;     /* 背景色     */
	background    : #ffffff;     /* 文字色     */
    }
    .loginbtn:hover {
    box-shadow    : none;        /* カーソル時の影消去 */
    color         : #556b2f;     /* 背景色     */
	background    : #ffffff;     /* 文字色     */
    }
    .logoutbtn:hover {
    box-shadow    : none;        /* カーソル時の影消去 */
    color         : #ff4500;     /* 背景色     */
	background    : #ffffff;     /* 文字色     */
    }
    .signup{
    margin: 5px 5px;
    padding: 5px 5px;
    width: 25%;
    background: white;
    border-top: solid 5px #5d627b;
    box-shadow: 0 3px 5px rgba(0, 0, 0, 0.22);
    }
    .login{
    margin: 5px 5px;
    padding: 5px 5px;
    width: 25%;
    background: white;
    border-top: solid 5px #556b2f;
    box-shadow: 0 3px 5px rgba(0, 0, 0, 0.22);
    }
    .in{
    margin: 5px 5px;
    padding: 5px 5px;
    width: 25%;
    background: white;
    border-top: solid 5px #ff4500;
    box-shadow: 0 3px 5px rgba(0, 0, 0, 0.22);
    }
    @media screen and (min-width: 480px) {
    }
    @media screen and (max-width: 479px) {
    .signup, .login{
    width: 80%;
    }
    .in{
    width: 40%;
    }
    p{
    font-size: medium;
    }
    .txt{
    font-size: small;
    }
    }
    </style>
  </head>
  <body>
  {% extends "DiaryApp/layout.html" %}
  {% block content %}
  <h1>MileageDiary</h1>
  
  <div class='main'>
  <p class='txt'>MileageDiary はクルマの走行距離や給油量、燃費、ガソリン代などを総合的に管理するためのWebアプリです。</p>
  <p class='txt'>記録したデータの一覧表示や、グラフ表示もできます。</p>  
  </div>
  {% if user.is_authenticated %}
  		<div class='link'>
  		<div class='in'>
        <p>Hello, {{ user.username }}</p>
        <a class="logoutbtn" href="{% url 'DiaryApp:logout' %}">ログアウト</a>
        </div>
        </div>
    {% else %}
        <div class='link'>
		<div class='signup'>
		<p>ユーザー登録はこちら</p>
		<a class="signupbtn" href="{% url 'DiaryApp:signup' %}">サインアップ</a>
		</div>
		<div class='login'>
		<p>アカウント作成済の方はこちら</p>
		<a class="loginbtn" href="{% url 'DiaryApp:login' %}">ログイン</a>
		</div>
		</div>
    {% endif %}

  {% endblock %}
  </body>
</html>

MileageDiaryWeb2/DiaryApp/templates/DiaryApp/log_create_form.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Log Create</title>
<style>
h1{
  margin: 5px 10px;
}
.f{
  margin: 5px 10px;
}
</style>
</head>
<body>
{% extends "DiaryApp/layout.html" %}
  {% block content %}
    <h1>Log 新規作成</h1>
    <form class='f' method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="保存">
    </form>
  {% endblock %}
</body>
</html>

MileageDiaryWeb2/DiaryApp/templates/DiaryApp/log_delete.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Log Delete</title>
</head>
<body>
{% extends "DiaryApp/layout.html" %}
{% block content %}
<h1>Log 削除確認画面</h1>
    <form method="post">
        {% csrf_token %}
        <p>{{ log.km }}/{{ log.litter }}/{{ log.price }}/{{ log.trip_memo }}を削除しますか？</p>
        <input type="submit" value="削除する">
    </form>
{% endblock %}
</body>
</html>

MileageDiaryWeb2/DiaryApp/templates/DiaryApp/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>DiaryApp Login</title>
<link href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" rel="stylesheet">
<style>
.social{
display: flex;
}
.my-skyblue{
color: #4385f5;
margin: 2px;
}
.my-black{
color: #1e1e1e;
margin: 2px;
}
.my-green{
color: #00B900;
margin: 2px;
}
.google{
 margin-left: 30px;
 color         : #ffffff;
 border        : 2px solid #4385f5;
}
.github{
 margin-left: 30px;
 color         : #ffffff;
 border        : 2px solid #1e1e1e;
}
.githubbtn{
color: #1e1e1e;
margin: 5px 5px;
}
</style>
</head>
<body>
{% extends "DiaryApp/layout.html" %}
{% block content %}
 <h2 style="margin:5px 30px">Login</h2>
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
 
{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}
 
<form style="margin:5px 30px" method="post" action="{% url 'DiaryApp:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>
 
<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
<br>
  <p style="margin:10px 30px"><strong>-- または --</strong></p>
  <div class="social">
  <span class="google">
  <i class="fab fa-google my-skyblue"></i><a style="margin:5px 5px" href="{% url 'DiaryApp:social:begin' 'google-oauth2' %}">Login with Google</a><br>
  </span>
  <span class="github">
  <i class="fab fa-github my-black"></i><a class="githubbtn" href="{% url 'DiaryApp:social:begin' 'github' %}">Login with GitHub</a><br>
  </span>
  </div>
{% endblock %}
</body>
</html>